language: node_js
node_js:
  - "node"
deploy:
  - skip_cleanup: true
    provider: script
    script: npm run deploy
    on:
      branch: feature/KA-400_Try_openapi-generator
  - skip_cleanup: true
    provider: script
