export const ADD_NODE = 'ADD_NODE';
export const TOGGLE_NODE = 'TOGGLE_NODE';
export const SAVE_NODE = 'SAVE_NODE';
export const DELETE_NODE = 'DELETE_NODE';

export const FETCH_NODES_REQUEST = 'FETCH_NODES_REQUEST';
export const FETCH_NODES_FAILURE = 'FETCH_NODES_FAILURE';
export const FETCH_NODES_SUCCESS = 'FETCH_NODES_SUCCESS';

export const POST_NODE_REQUEST = 'POST_NODE_REQUEST';
export const POST_NODE_FAILURE = 'POST_NODE_FAILURE';
export const POST_NODE_SUCCESS = 'POST_NODE_SUCCESS';

export const DELETE_NODE_REQUEST = 'DELETE_NODE_REQUEST ';
export const DELETE_NODE_FAILURE = 'DELETE_NODE_FAILURE';
export const DELETE_NODE_SUCCESS = 'DELETE_NODE_SUCCESS ';

export const DELETE_ERROR = 'DELETE_ERROR';
