export const ADD_NODE = 'ADD_NODE';
export const TOGGLE_NODE = 'TOGGLE_NODE';
export const SAVE_NODE = 'SAVE_NODE';
export const DELETE_NODE = 'DELETE_NODE';

export const FETCH_NODES_REQUEST = 'FETCH_NODES_REQUEST';
export const FETCH_NODES_FAILURE = 'FETCH_NODES_FAILURE';
export const FETCH_NODES_SUCCESS = 'FETCH_NODES_SUCCESS';

export const REMOVE_ERROR = 'REMOVE_ERROR';


