export const TOGGLE_NODE = 'TOGGLE_NODE';

export const GET_NODES_START = 'GET_NODES_START';
export const GET_NODES_FAILURE = 'GET_NODES_FAILURE';
export const GET_NODES_SUCCESS = 'GET_NODES_SUCCESS';

export const ADD_NODE_START = 'ADD_NODE_START';
export const ADD_NODE_FAILURE = 'ADD_NODE_FAILURE';
export const ADD_NODE_SUCCESS = 'ADD_NODE_SUCCESS';
export const ADD_NODE_OPTIMISTIC = 'ADD_NODE_OPTIMISTIC';

export const DELETE_NODE_START = 'DELETE_NODE_START ';
export const DELETE_NODE_FAILURE = 'DELETE_NODE_FAILURE';
export const DELETE_NODE_SUCCESS = 'DELETE_NODE_SUCCESS ';

export const UPDATE_NODE_START = 'UPDATE_NODE_START';
export const UPDATE_NODE_FAILURE = 'UPDATE_NODE_FAILURE';
export const UPDATE_NODE_SUCCESS = 'UPDATE_NODE_SUCCESS';

export const DISMISS_ERROR = 'DISMISS_ERROR';
